### ISSUE TITLE
Using tilt_angle attributes even if tilt_angle doesn't exist

### ISSUE THREAD

**Issue by ajcse1** [jaws/jaws#135]
Interestingly, if I select only the uppermost 10 lines, I get

kuipersm@:~/Data/AWS/Antarctica/AWS17> jaws --rigb -4 -o ant_aws17_final_year2011_TEST.nc ant_aws17_goodangles.txt
Traceback (most recent call last):
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 780, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'tilt_direction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/bin/jaws", line 11, in <module>
    sys.exit(start())
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/jaws.py", line 257, in start
    main(parse_args(sys.argv[1:]))
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/jaws.py", line 244, in main
    dispatch_converter(args, input_file, output_file, stations)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/jaws.py", line 213, in dispatch_converter
    converters[char](args, input_file, output_file, stations)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/imau2nc.py", line 188, in imau2nc
    common.load_dataset_attributes(sub_type, ds, args)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/common.py", line 151, in load_dataset_attributes
    ds[key1].attrs = value2.items()
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 874, in __getitem__
    return self._construct_dataarray(key)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 783, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 77, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'tilt_direction'
kuipersm@:~/Data/AWS/Antarctica/AWS17> jaws --rigb -4 -o ant_aws17_final_year2011_TEST.nc ant_aws17_goodangles.txt
Traceback (most recent call last):
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 780, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'tilt_direction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/bin/jaws", line 11, in <module>
    sys.exit(start())
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/jaws.py", line 257, in start
    main(parse_args(sys.argv[1:]))
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/jaws.py", line 244, in main
    dispatch_converter(args, input_file, output_file, stations)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/jaws.py", line 213, in dispatch_converter
    converters[char](args, input_file, output_file, stations)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/imau2nc.py", line 188, in imau2nc
    common.load_dataset_attributes(sub_type, ds, args)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/jaws/common.py", line 151, in load_dataset_attributes
    ds[key1].attrs = value2.items()
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 874, in __getitem__
    return self._construct_dataarray(key)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 783, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims)
  File "/Users/kuipersm/Library/Enthought/Canopy/edm/envs/User/lib/python3.5/site-packages/xarray/core/dataset.py", line 77, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'tilt_direction'

_Originally posted by @pkuipersmunneke in https://github.com/jaws/jaws/issues/133#issuecomment-448967016_

**Comment by ajcse1** [comment]
Fixed in v0.6.4
