### ISSUE TITLE
jaws pegs CPU and hangs on MacOS laptop

### ISSUE THREAD

**Issue by czender** [jaws/jaws#18]
Killed after many minutes on MacOS X miniconda environment:
```
zender@aerosol:~/jaws/source$ python jaws.py ../sample_data/gcnet_20130101.txt
^CTraceback (most recent call last):
  File "jaws.py", line 32, in <module>
    Main()
  File "jaws.py", line 20, in Main
    gcnet2nc.gcnet2nc(args)
  File "/Users/zender/jaws/source/gcnet2nc.py", line 10, in gcnet2nc
    f.readline()
KeyboardInterrupt
zender@aerosol:~/jaws/source$ which python
/Users/zender/anaconda/bin/python
```
It could be an issue of my environment variables? May need to document common pitfalls for naive Python users like me. In any case, I need help getting jaws to run as advertised.

**Comment by ajcse1** [comment]
It is working now. There was a iteration issue in loop.
