### ISSUE TITLE
Output to netCDF classic formats fails

### ISSUE THREAD

**Issue by czender** [jaws/jaws#23]
As shown below. I think you know this already. What you may not know it the reason why: netCDF formats 3, 5, 6, and 7 cannot store text as strings. Instead, text values must be stored as 1-D character arrays. Hence you need to define an arbitrary dimension size, e.g., max_txt_lng=100, and define the variable of character type with dimension [max_txt_lng] or, in some cases, [time,max_txt_lng].

```
zender@aerosol:~/jaws/source$ python jaws.py -f 3 ../sample_data/gcnet_20130101.txt
Traceback (most recent call last):
  File "jaws.py", line 31, in <module>
    Main()
  File "jaws.py", line 19, in Main
    gcnet2nc.gcnet2nc(args)
  File "/Users/zender/jaws/source/gcnet2nc.py", line 46, in gcnet2nc
    station_number = root_grp.createVariable('station_number', 'u1', ('time',))
  File "netCDF4/_netCDF4.pyx", line 2437, in netCDF4._netCDF4.Dataset.createVariable
  File "netCDF4/_netCDF4.pyx", line 3389, in netCDF4._netCDF4.Variable.__init__
  File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

```

**Comment by ajcse1** [comment]
Done. #11
