### ISSUE TITLE
ValueError('%r is not callable' % (type_func,))

### ISSUE THREAD

**Issue by czender** [jaws/jaws#53]
The input file does exist and the error message is inscrutable.

```
zender@grele:~/anaconda/bin$ python ~/jaws/source/jaws.py ~sainiak/data/jaws/gcnet/raw/gcnet_summit_19960512_20170524.dat_Req1666 ~/data/jaws/gcnet/gcnet_summit_19960512_20170524.nc
Traceback (most recent call last):
  File "/home/zender/jaws/source/jaws.py", line 311, in <module>
    Main()
  File "/home/zender/jaws/source/jaws.py", line 20, in Main
    parser.add_argument("-t","--timezone", help = "Change the timezone, default is UTC", default='UTC', type='str')
  File "/home/zender/anaconda/lib/python2.7/argparse.py", line 1299, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'str' is not callable
zender@grele:~/anaconda/bin$ ls -l ~sainiak/data/jaws/gcnet/raw/gcnet_summit_19960512_20170524.dat_Req1666
-rw-rw-r-- 1 sainiak sainiak 62140412 Jan 30 22:09 /home/sainiak/data/jaws/gcnet/raw/gcnet_summit_19960512_20170524.dat_Req1666

```

**Comment by ajcse1** [comment]
Resolved the error. Now working for all networks.
